# Generated by Django 4.1.6 on 2023-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('content', models.CharField(max_length=500, verbose_name='')),
            ],
        ),
    ]
