# Generated by Django 4.1.7 on 2023-02-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('diary_web', '0002_write'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('color', models.CharField(default='#0071c5', max_length=7)),
            ],
            bases=('schedule.event',),
        ),
        migrations.AlterField(
            model_name='write',
            name='content',
            field=models.CharField(max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='write',
            name='date',
            field=models.DateField(verbose_name='Y%-m%-d%'),
        ),
    ]
